# Generated by Django 4.1.7 on 2023-10-23 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('tipo', models.CharField(choices=[('fisica', 'fisica'), ('juridica', 'juridica')], max_length=10)),
                ('numero_documento', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=80)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('excluido', models.BooleanField(default=False)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pessoas_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('gerador', 'gerador'), ('veiculo', 'veiculo'), ('iluminacao', 'iluminacao'), ('geral', 'geral')], default='geral', max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('proprietario', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=80)),
                ('numero_serie', models.CharField(max_length=20)),
                ('marca_modelo', models.CharField(max_length=80)),
                ('cor', models.CharField(max_length=20)),
                ('ano_fabricacao', models.CharField(max_length=4)),
                ('combustivel', models.CharField(max_length=20)),
                ('restricoes', models.TextField(blank=True, null=True)),
                ('potencia', models.IntegerField(blank=True, null=True)),
                ('horimetro', models.CharField(blank=True, max_length=20, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponivel', 'disponivel'), ('indisponivel', 'indisponivel')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, default=False, max_length=500, null=True)),
                ('placa', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('uf', models.CharField(max_length=2)),
                ('proprietario', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=80)),
                ('chassi', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('marca_modelo', models.CharField(max_length=80)),
                ('cor', models.CharField(max_length=20)),
                ('ano_fabricacao', models.CharField(max_length=4)),
                ('ano_modelo', models.CharField(max_length=4)),
                ('carroceria', models.CharField(max_length=20)),
                ('combustivel', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('licenciamento', models.CharField(max_length=4)),
                ('restricoes', models.TextField(blank=True, null=True)),
                ('odometro', models.CharField(blank=True, max_length=20, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponivel', 'disponivel'), ('indisponivel', 'indisponivel')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('requerido', models.CharField(blank=True, max_length=40, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
                ('itens_defeito', models.ManyToManyField(blank=True, to='core.defeito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_admissao', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios_fotos')),
                ('excluido', models.BooleanField(default=False)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defeito',
            name='item_defeito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemservico'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('data', models.DateField()),
                ('validade', models.DateField()),
                ('exercicio', models.CharField(max_length=4)),
                ('horimetro', models.CharField(blank=True, max_length=20, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
