# Generated by Django 4.1.7 on 2023-10-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_veiculo_carroceria_remove_veiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('gerador', 'gerador'), ('veiculo', 'veiculo'), ('iluminacao', 'iluminacao'), ('geral', 'geral')], default='geral', max_length=10),
        ),
    ]
