# Generated by Django 4.1.7 on 2023-10-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_veiculo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('gerador', 'gerador'), ('veiculo', 'veiculo'), ('iluminacao', 'iluminacao'), ('geral', 'geral')], default='veiculo', max_length=10),
        ),
    ]
