# Generated by Django 4.1.7 on 2023-10-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_veiculo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='data',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='exercicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='horimetro',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='validade',
        ),
        migrations.AddField(
            model_name='contrato',
            name='condicoes_especificas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='deposito_seguranca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos_contrato/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='equipamento',
            field=models.CharField(default='Gerador', max_length=50),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado_inicial_gerador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='local_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='potencia_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='servicos_inclusos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='taxas_adicionais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
