# Generated by Django 4.1.7 on 2023-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contrato_data_remove_contrato_exercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.AddField(
            model_name='contrato',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
