# Generated by Django 4.1.7 on 2023-11-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contrato_cliente_contrato_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='usuario',
        ),
    ]
