# Generated by Django 4.1.7 on 2023-11-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_servico_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='itens_defeito',
        ),
    ]
