# Generated by Django 4.1.7 on 2023-11-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_servico_itens_defeito'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='itens_servico',
            field=models.ManyToManyField(blank=True, to='core.itemservico'),
        ),
    ]
