# Generated by Django 4.1.7 on 2023-11-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_rename_itens_servico_servico_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='servico',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='servico',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
