# Generated by Django 4.1.7 on 2023-11-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_funcionario_user_alter_servico_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='requerido',
        ),
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
