# Generated by Django 4.1.7 on 2023-11-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_servico_requerido_servico_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Defeito',
        ),
    ]
