# Generated by Django 4.1.7 on 2023-11-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0015_delete_defeito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='object_id',
            new_name='equipamento_veiculo_id',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='content_type',
        ),
        migrations.AddField(
            model_name='servico',
            name='equipamento_veiculo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
