# Generated by Django 4.1.7 on 2023-11-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_object_id_servico_equipamento_veiculo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='equipamento_veiculo_id',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='equipamento_veiculo_type',
        ),
        migrations.AddField(
            model_name='servico',
            name='equipamento',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
