# Generated by Django 4.1.7 on 2023-11-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_servico_equipamento_veiculo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.veiculo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
    ]
