# Generated by Django 4.1.7 on 2023-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_servico_funcionario_servico_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='parecer',
            field=models.CharField(blank=True, choices=[('aprovado', 'aprovado'), ('aprovado_com_ressalva', 'aprovado_com_ressalva'), ('pendente', 'pendente'), ('reprovado', 'reprovado')], max_length=30, null=True),
        ),
    ]
