# Generated by Django 4.1.7 on 2023-11-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='marca_modelo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='potencia_kw',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='horas_funcionando',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('funcionando', 'funcionando'), ('standby', 'standby')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'pix'), ('dinheiro', 'dinheiro'), ('deposito', 'deposito'), ('cartao_credito', 'cartao_credito'), ('cartao_debito', 'cartao_debito')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_equipamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
    ]
