# Generated by Django 4.1.7 on 2023-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_contrato_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
