# Generated by Django 4.1.7 on 2023-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_servico_content_type_remove_servico_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
